// src/index.js
import { createClerkClient } from '@clerk/backend';

export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    // Route guard for protected pages
    if (url.pathname.startsWith('/vr')) {
      const cookieHeader = request.headers.get('Cookie') || '';
      const sessionToken = cookieHeader
        .split(';')
        .map((c) => c.trim())
        .find((c) => c.startsWith('__session='))
        ?.split('=')[1];

      if (!sessionToken) {
        return Response.redirect(`${url.origin}/`, 302);
      }

      const clerk = createClerkClient({ secretKey: env.CLERK_SECRET_KEY });
      try {
        await clerk.authenticateRequest(request, {
          publishableKey: env.CLERK_PUBLISHABLE_KEY,
          secretKey: env.CLERK_SECRET_KEY,
        });
      } catch {
        return Response.redirect(`${url.origin}/`, 302);
      }
    }

    // Serve static files generated by Vite
    return env.ASSETS.fetch(request);
  },
};